name: Automated API tests using Postman CLI

on: [push, pull_request]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install Postman CLI
        # run: |
        #   curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      # - name: Login to Postman CLI
      #   apiKey: postman login --with-api-key PMAK-67ed0433c84a6f00015b2751-9b7ee838be1c0ea62425effe6c58ef4ead
      # - name: Run API tests
      #   run: |
      #     postman collection run "27932117-7c8d245d-75a4-475c-8963-f4723e0f562e"
      - name: Run API Test
        run: newman run "newman_test.json" -r htmlextra
