name: Automated API tests using Postman CLI

on: [push, pull_request]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra    
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run API Test
        run: newman run "newman_test.json" -r htmlextra 
      - name: debug
        run: |
          pwd
          ls -la newman      
      - name: Output the results
        uses: actions/upload-artifact@v4
        with:
          name: htmlreport
          path: newman/*

